### ISSUE TITLE
Reboots on #[EB|LOG:EXITBS:START]

### ISSUE THREAD

**Issue by brandonplank** [arch-dev/DellInspiron5767Hackintosh#10]
* Latest macOS version
* BIOS 1.5.0
* OpenCore 0.8.0

**Comment by brandonplank** [comment]
Here is the last bit before it reboots, had to use a slow mode camera to get it
![image](https://user-images.githubusercontent.com/52553007/171294210-4b023b4c-77cd-4eb5-97a3-e6d26b0de6c7.png)

**Comment by arch-dev** [comment]
I think there is something wrong with your config.plist. Can you upload it so I can compare it with mine, please? Thank you.

**Comment by crypticplank** [comment]
It's the exact same, except for the the system uuid and stuff.

**Comment by crypticplank** [comment]
I ran OC validate and it came up with nothing wrong.

**Comment by brandonplank** [comment]
The only thing i can think of, that may effect it, is that I removed the battery and disk drive due to errors and swelling.

**Comment by brandonplank** [comment]
* [config.txt](https://github.com/arch-dev/DellInspiron5767Hackintosh/files/8818406/config.txt)
Dont mind the txt, had to use it so Github would allow the upload

This has to help, the highest log level
* [opencore-2022-06-01-141922.txt](https://github.com/arch-dev/DellInspiron5767Hackintosh/files/8818861/opencore-2022-06-01-141922.txt)

* Entire EFI Folder https://cdn.brandonplank.org/EFI.zip

Also note, I am using a SSD and ive already tried the NVME kext without any luck as well.

**Comment by crypticplank** [comment]
Entire EFI Folder https://cdn.brandonplank.org/EFI.zip

**Comment by brandonplank** [comment]
its not cfg lock
it cant be cfg lock
it was cfg lock
