### ISSUE TITLE
Massive performace issues

### ISSUE THREAD

**Issue by brandonplank** [arch-dev/DellInspiron5767Hackintosh#7]
Using any thing that remotely requires any processing power is really sluggish.

Im talking mostly about xcode and multitasking.

**Comment by brandonplank** [comment]
This was non-existent in catalina

**Comment by arch-dev** [comment]
Sorry for the late answer but I've been busy with my exams. I've updated all the installation files for Monterey. For now it seems that performances are good. If you can test and report again I'll appreciate that. Thank you.
