### ISSUE TITLE
HDMI Broken

### ISSUE THREAD

**Issue by brandonplank** [arch-dev/DellInspiron5767Hackintosh#8]
HDMI is broken in Monterey.

**Comment by brandonplank** [comment]
The only thing it does, when you plug in the external display, it just turns black for a second and does nothing

**Comment by arch-dev** [comment]
I'm currently testing a fix for this. I'll check framebuffer connectors values and upload a working config shortly.

**Comment by brandonplank** [comment]
Thanks :)

**Comment by brandonplank** [comment]
This issue is fixed in your latest release
